version: '3.4'

services:
  urlshortener:
    image: urlshortener
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
  redisdb:
    image: redis:alpine3.16